### PR TITLE
Verify session and revoke session were using incorrect endpoints.

### PR DESCRIPTION
**Pull request by secondsun**

### CODE REVIEW

**Comment by secondsun** [comment]
@wei-lee @danielpassos :eyes:?

**Comment by wei-lee** [comment]
looks good. Good catch Summers. No idea how it was wrong before.

**Comment by danielpassos** [comment]
:+1:

**Comment by danielpassos** [comment]
https://github.com/feedhenry/fh-android-sdk/commit/f88ad302243a49edf930b1809dc2b9d57a9c5082

landed

**Pull request closed without merging**
