### PR TITLE
Remove json source and add it as a Maven dependency

### PR DESCRIPTION
**Pull request by danielpassos**
See [FHMOBSDK-29](https://issues.jboss.org/browse/FHMOBSDK-29)

### CODE REVIEW

**Comment by danielpassos** [comment]
Rebased! The test 14 is failing on travis, but it works on my machine :angry:

**Comment by wei-lee** [comment]
Let me try it

**Comment by wei-lee** [comment]
@danielpassos  I got the exactly same issue as on Travis. Let me see if I can fix this.

**Comment by wei-lee** [comment]
@danielpassos I have tried to fix the issue with the failing sync test here: https://github.com/feedhenry/fh-android-sdk/commit/312f691076d0a78519f725fccbb18a2b54adf699.

However, I still can't get the test passing as it seems that even I specified the org.json dependency in the pom.xml file, when the app (test) is running on the device, it kept using Android's own org.json library.

Any idea?

**Comment by danielpassos** [comment]
@wei-lee Nopz. I'll try fix it tomorrow

**Comment by wei-lee** [comment]
@danielpassos any luck? I even tried to include the source of org.json in the project, but still no luck unless I change the package name to something else.

**Comment by danielpassos** [comment]
Hrm, weird! I have no idea what is wrong. The tests is passing on `Genymotion` and on my `Nexus 5` :disappointed:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Feedhenry Android SDK Parent ...................... SUCCESS [0.157s]
[INFO] Feedhenry Android SDK Library ..................... SUCCESS [8.863s]
[INFO] FeedHenry Android SDK Test ........................ SUCCESS [58.513s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:08.705s
[INFO] Finished at: Wed Mar 11 09:40:24 BRT 2015
[INFO] Final Memory: 38M/149M
[INFO] --------------------------------------------------------------------
```

I'm closing that for now to investigate.

**Comment by wei-lee** [comment]
yeah, it is strange. I am getting the errors locally too.

**Comment by secondsun** [comment]
@secondsun tagging myself so I will remember to chekc this out

**Comment by kpiwko** [comment]
Hello guys,

we've hit the similar problem while packaging json/gson in app via Selendroid instrumentation. It has not been working on Android 4 but it was working on Android 5 - it's due to different classloaders used in Dalvik and ART. Our solution was to replace serialization with custom code - https://github.com/selendroid/selendroid/pull/770

**Pull request closed without merging**
