### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by danielpassos**

### CODE REVIEW

**Comment by matzew** [comment]
do we really need to check in a depedency ?

**Comment by danielpassos** [comment]
@matzew Not sure what kind of check you mean. Are you talking about @travis-ci? Or a review?

**Comment by danielpassos** [comment]
@matzew Sorry check in I've read check :package: 

ANT project need that, because it can not use `aar`. See: https://github.com/feedhenry/fh-android-sdk#ant-projects

**Comment by matzew** [comment]
Ah, thanks for the heads-up, @danielpassos  :kissing:

**Pull request merged**
