### PR TITLE
Prepare to release

### PR DESCRIPTION
**Pull request by danielpassos**
This PR create a specific commit to tag a `2.1.0` release

### CODE REVIEW

**Comment by wei-lee** [comment]
@danielpassos  build failed. do you need to update the version in the pom file in fh-android-sdk and fh-adnroid-sdk-test too?

**Comment by danielpassos** [comment]
Of course. My fail. Let me fix that.

**Comment by danielpassos** [comment]
Fixed

**Comment by wei-lee** [comment]
Reviewed.

**Pull request merged**
