### PR TITLE
Add AeroGear Android Push library

### PR DESCRIPTION
**Pull request by danielpassos**

### CODE REVIEW

**Comment by secondsun** [comment]
Other than including the library is this supposed to do anything?

**Comment by danielpassos** [comment]
@secondsun in SDK I think no, but probably in build farm. See [FH-120](https://issues.jboss.org/browse/FH-120)

**Comment by matzew** [comment]
@wei-lee @jasonmadigan Getting this in will very helpful for https://issues.jboss.org/browse/FH-11 (the Android part)

So, that push enabled FH apps, get the registration library automatically. 

I think on the FH SDK side, we could do a little bit of improvements on the configration (of variantID/secret), as discussed here: https://issues.jboss.org/browse/FH-239

**Comment by wei-lee** [comment]
@danielpassos @matzew @jasonmadigan @secondsun Similar to the [same iOS SDK PR](https://github.com/feedhenry/fh-ios-sdk/pull/32), I am not sure this is a good idea to include the AG push SDK as a dependency while it is not the case at all. We should only do this when we decide to deeply integrate the FH SDK and the AG SDK.

As I said in the comments of the ios PR, for now, we should update build farm to include the AG push sdk automatically when push notification is enabled in the studio.

**Comment by matzew** [comment]
@danielpassos @jasonmadigan @secondsun added a related comment to the iOS PR

**Comment by secondsun** [comment]
linking to ios pr : https://github.com/feedhenry/fh-ios-sdk/pull/32

**Comment by danielpassos** [comment]
This PR was add in a new one https://github.com/feedhenry/fh-android-sdk/pull/28

**Pull request closed without merging**
