### PR TITLE
Json package optimisations

### PR DESCRIPTION
**Pull request by psyren89**
This PR ports across updates made to the JSON package in [the original repo](https://github.com/douglascrockford/JSON-java), as well as general code formatting.

### CODE REVIEW

**Comment by secondsun** [comment]
@psyren89 Can you resubmit the PR to the FH-v3.8.0 branch?  That is the current feature development branch.

**Comment by psyren89** [comment]
@secondsun will do.

**Comment by psyren89** [comment]
If the ultimate goal is to use a better maintained 3rd party library, is there any point in me reopening this PR?

**Comment by matzew** [comment]
> If the ultimate goal is to use a better maintained 3rd party library, is there any point in me reopening this PR?

@psyren89 I think it might make sense for the 3.x series, but I think for 4.x we should get rid of the JSON.org packages, and use something that's available as a dependency via Maven, and also better maintained.

Also, the JSON.org stuff has a pretty [bogus, non-free license](http://www.gnu.org/licenses/license-list.html#JSON):
See here in the header:
https://github.com/feedhenry/fh-android-sdk/blob/master/fh-android-sdk/src/main/java/org/json/fh/HTTP.java#L16

**Pull request closed without merging**
