### PR TITLE
Adding unregister method and bumping agdroid-push version

### PR DESCRIPTION
**Pull request by secondsun**
@danielpassos @matzew :eyes: 

# Testing instructions

Ping me on IRC.

### CODE REVIEW

**Comment by secondsun** [comment]
@danielpassos @matzew Just poking you guys :)

**Comment by danielpassos** [comment]
Tested using http://testing.supittma.skunkhenry.com/#/projects/u5ekwqf7jbjunuwhbxa4thmm/apps

**Comment by matzew** [comment]
@edewit @corinnekrych do we need to integrate this into Cordova-Android too ? so that folks can use it from there too ?

**Comment by danielpassos** [comment]
@matzew Yes and we already have an issues for it :)

**Pull request merged**
