### PR TITLE
Removing unused class

### PR DESCRIPTION
**Pull request by matzew**
@danielpassos mind to do a quick review ?

### CODE REVIEW

**Comment by danielpassos** [comment]
:+1:

**Comment by matzew** [comment]
@danielpassos @wei-lee anyone merging this ?

**Comment by wei-lee** [comment]
@matzew will do it. You should have the permission to merge it?

**Comment by matzew** [comment]
Since I submitted it thought it's nice to have someone else merge it ;-)

On Fri, Jul 24, 2015 at 11:08 AM, Wei Li <notifications@github.com> wrote:

> @matzew <https://github.com/matzew> will do it. You should have the
> permission to merge it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/feedhenry/fh-android-sdk/pull/32#issuecomment-124450583>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by matzew** [comment]
:kissing_heart:

**Pull request merged**
