### PR TITLE
Notice file and licenses

### PR DESCRIPTION
**Pull request by matzew**
* Updating FH license headers on Java/xml files, via license-plugin (added a `rht_mobile_license_header.txt` file) and replaced proprietary FH header w/ Red Hat / Apache-2 
* Added `NOTICE` file about used dependencies, and src includes

### CODE REVIEW

**Comment by matzew** [comment]
@johnfriz please review

**Comment by matzew** [comment]
@johnfriz any comments ?

**Comment by johnfriz** [comment]
@matzew - Are we sure we want this to be copyright Red Hat?

This will be the "FeedHenry" community repo / code. The productized version can be copyright Red Hat, but not sure if this repo should be?

Thoughts?

**Comment by matzew** [comment]
sure, why not?
We do that on several of our OSS repos. RHT keeps the copyright, while licensing under Apache version2. Nothing speaks against that.

Examples:
* https://github.com/wildfly-swarm/wildfly-swarm/blob/master/webservices/api/src/main/java/org/wildfly/swarm/webservices/WebServicesRuntimeModuleProvider.java#L2
* https://github.com/hawkular/hawkular/blob/master/modules/hawkular-wildfly-agent-download/src/main/java/org/hawkular/component/wildflymonitor/WildFlyAgentServlet.java#L2

but the year inclusion sucks :-)

So at AeroGear we do simply:
* https://github.com/aerogear/aerogear-unifiedpush-server/blob/master/jaxrs/src/main/java/org/jboss/aerogear/unifiedpush/rest/sender/PushNotificationSenderEndpoint.java#L3

**Comment by matzew** [comment]
@johnfriz ready to merge ?

**Comment by johnfriz** [comment]
@matzew - Merge away :smile:

**Comment by matzew** [comment]
:shipit:  :)

**Pull request merged**
