### PR TITLE
Remove methods deprecated in FH3.7.0

### PR DESCRIPTION
**Pull request by secondsun**
We deprecated a bunch of methods in 3.7.0.  This PR removes them for 3.8.0.

Big notes

 * Removes execute and executeAsync from FHHttpClient and replaces them with an asynchronous execute method.
 * Removes many static methods from FHAct, FHRemote, and FHAuth classes.

# How to test
 * Run mvn clean install while a android device is plugged in.

### CODE REVIEW

**Comment by secondsun** [comment]
@wei-lee @danielpassos What do you guys think?  THis PR removes a bunch of things we decided to remove, but it may be too soon for some people's tastes.

**Comment by danielpassos** [comment]
@wei-lee Any objection?

**Comment by wei-lee** [comment]
which version are we planning to release this? I don't have problem with removing functions. We just need to make sure this change is  properly communicated.

**Comment by secondsun** [comment]
Given the feedback on internal lists, I think we should close this for now until we get a more official deprecation policy.

**Pull request closed without merging**
