### PR TITLE
Migrating to FCM

### PR DESCRIPTION
**Pull request by secondsun**
@matzew @matskiv @danielpassos :eyes: ?

### CODE REVIEW

**Comment by danielpassos** [comment]
@secondsun LGTM, just wondering if we not should wait for the AeroGear release instead of use `SNAPSHOT`

**Comment by matzew** [comment]
yeah, thats the plan ;)

On Thursday, 9 June 2016, Daniel Passos <notifications@github.com> wrote:

> @secondsun <https://github.com/secondsun> LGTM, just wondering if we not
> should wait for the AeroGear release instead of use SNAPSHOT
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/feedhenry/fh-android-sdk/pull/95#issuecomment-224860615>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAJnzlUlGgvCeBa7rymOit9KjpPen41Yks5qJ-7lgaJpZM4IxCvv>
> .
>


-- 
Sent from Gmail Mobile

**Comment by matzew** [comment]
@secondsun here is the update to the released shindig:
https://github.com/secondsun/fh-android-sdk/pull/2

**Comment by secondsun** [comment]
@matzew @danielpassos Time to stage?

**Pull request merged**
