### PR TITLE
Javadoc fixes

### PR DESCRIPTION
**Pull request by secondsun**
Fix for FHMOBSDK-26. 

To test just `mvn clean install` with JDK 8

### CODE REVIEW

**Comment by danielpassos** [comment]
```
[passos]: ~/Development/Projects/FeedHenry/fh-android-sdk [git:pr/16]  
→ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

[passos]: ~/Development/Projects/FeedHenry/fh-android-sdk [git:pr/16]  
→ mvn clean install
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Feedhenry Android SDK Parent ...................... SUCCESS [0.094s]
[INFO] Feedhenry Android SDK Library ..................... SUCCESS [11.854s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.823s
[INFO] Finished at: Fri Feb 20 22:07:57 BRST 2015
[INFO] Final Memory: 33M/390M
[INFO] ------------------------------------------------------------------------
```

**Comment by danielpassos** [comment]
@secondsun Sent https://github.com/secondsun/fh-android-sdk/pull/1 to add Java 8 on @travis-ci and travis [like](https://travis-ci.org/danielpassos/fh-android-sdk/builds/51590280) that

**Comment by secondsun** [comment]
@wei-lee thoughts?

**Comment by wei-lee** [comment]
:clap: @secondsun Looks good to me.

**Pull request merged**
